name: Bot Jipa Speed
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Restore Session Cache
        uses: actions/cache@v3
        with:
          path: ./auth_info_baileys
          key: ${{ runner.os }}-session-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-session-

      - name: Install Dependencies
        run: |
          npm install --omit=optional --ignore-scripts
          npm install @ffmpeg-installer/ffmpeg

      - name: Start Bot
        run: NODE_SKIP_PLATFORM_CHECK=1 npx ts-node --transpile-only examples/bot.ts
